### PR TITLE
trying to shorten scraping code

### PR DESCRIPTION
**Pull request by bbelderbos**

### CODE REVIEW

**Comment by bbelderbos** [comment]
@BenGriffith cannot share gpt thread with images in them yet ("Sharing conversations with images is not yet supported")

Can you check accuracy? 

Your initial version:

(Pdb) len(united_states_tollways)
29
(Pdb) len(united_states_tollways.values())
29
(Pdb) sum(len(a) for a in united_states_tollways.values())
170

My version:

(Pdb) len(united_states_tollways)
30
(Pdb) sum(len(a) for a in united_states_tollways.values())
190

**Comment by bbelderbos** [comment]
And could use a walrus :)

https://twitter.com/bbelderbos/status/1720502899422142557

**Review by BenGriffith — APPROVED** [review]

**Comment by BenGriffith** [comment]
I added a small check to remove h2 that is not a state/territory from being processed. Code was picking up the h2 'Jurisdictions without toll roads' at the very end causing the count difference of 1 between 29 and 30. 

Screenshot 2023-11-05 at 10 43 37 PM

**Comment by bbelderbos** [comment]
Great, that explains, thanks.

What about 

(Pdb) sum(len(a) for a in united_states_tollways.values())
170

vs

(Pdb) sum(len(a) for a in united_states_tollways.values())
190

**Comment by BenGriffith** [comment]
Reviewed webpage and updated results (190) a few minutes and 190 is the correct value. I had only done a few spot checks on code producing 170 so possible had a bug wasn't aware of.

**Comment by bbelderbos** [comment]
nice, thanks

**Pull request merged**
